CREATE TABLE IF NOT EXISTS schema_migrations(version TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO schema_migrations(version) VALUES ('001');
CREATE TABLE IF NOT EXISTS lessons(id TEXT PRIMARY KEY, school TEXT NOT NULL, title TEXT NOT NULL);
